### ISSUE TITLE
Logo not visible properly when page scrolled down

### ISSUE THREAD

**Issue by Jaybhade** [Jaybhade/aciie-web#7]
![Screenshot (181)_LI](https://user-images.githubusercontent.com/52350067/126890540-7892913a-3552-4fde-9e72-7a071d7571d4.jpg)

**Comment by sharma467sachin** [comment]
https://github.com/Jaybhade/aciie-web/pull/8

**Comment by sharma467sachin** [comment]
https://github.com/Jaybhade/aciie-web/pull/8

logo issue fixed
